name: Pano
main: com.panomc.plugins.pano.spigot.SpigotMain
version: ${version}
author: Pano MC
description: An advanced web platform for Minecraft servers.
website: http://panomc.com
api-version: '1.13'
folia-supported: true
#commands:
#  pano:
#    description: Runs Pano commands.
#    permission: pano.admin
#    permission-message: You do not have permission!
#  link:
#    description: Link your account with website.
#    default: true
permissions:
  pano.admin:
    description: Allows Pano command.
    default: op
  pano.*:
    description: Allows everything in Pano.
    default: op
    children:
      pano.admin: true
softdepend: [ AuthMe, LuckPerms ]
